version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: python3 hello.py
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: python3 hello.py

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test

